import { ThesisData } from './thesis-types'

export const thesisData: ThesisData = {
  title: 'Dynamic Heterogeneous Flight Graphs for AAM Security',
  subtitle: 'A graph neural network approach to risk modeling and security analysis for Advanced Air Mobility (AAM) systems using heterogeneous flight data.',
  lastUpdated: '2026-03-24',
  phases: [
    // ============================================================
    // FOUNDATIONAL RESEARCH (Pre-Jan 2026)
    // ============================================================
    {
      id: 'foundational-research',
      title: 'Initial Research & Scoping',
      dateRange: 'Nov 2025 – Jan 2026',
      summary: 'Initial literature review, data source evaluation, model architecture design, and methodology decisions that shaped the project. Several decisions made here were later revised as the project evolved — superseded items are noted.',
      outcome: 'Established the starting architecture and research foundation. Many specific decisions (update pattern, graph structure, training labels) were later revised through the timeline below.',
      outcomeType: 'foundation',
      entries: [
        {
          id: 'data-source-evaluation',
          date: '2025-11-01',
          title: 'Data Source Evaluation',
          type: 'research',
          summary: 'Surveyed available aircraft trajectory and accident/incident datasets. AAM-specific data is scarce (mostly simulators), so the approach uses conventional aircraft surveillance data.',
          keyFindings: [
            'Aircraft trajectory: OpenSky Trino (real, global, 2014-present) selected as primary — ADS-B/Mode-S with full state vectors',
            'Other trajectory sources evaluated: adsb.lol, TrajAir (CMU), NASA ATom, UAM-SUMO (synthetic), BlueSky ATM (synthetic)',
            'Accident data: NTSB Aviation Database (US, 1962-present) selected as primary',
            'Other accident sources evaluated: TSB Canada, NASA ASRS',
            'Key constraint: AAM-specific real-world data essentially does not exist yet',
          ],
          ledTo: ['usable-data-definition', 'initial-architecture'],
          tags: ['data-sources', 'opensky', 'ntsb'],
        },
        {
          id: 'literature-review-patterns',
          date: '2025-11-15',
          title: 'Literature Review — Dynamic GNN Patterns',
          type: 'research',
          summary: 'Reviewed 30 papers across Dynamic GNNs, Temporal Knowledge Graphs, and dynamic heterogeneous graphs. Identified three recurring architectural patterns for handling temporal graph data.',
          body: 'The review spanned 5 categories: surveys & taxonomies (6 papers), dynamic multi-relational/TKG methods (7), dynamic heterogeneous graph methods (6), general dynamic GNN methods (6), and aviation/transportation applications (5). Each paper was tagged by which pattern it follows and assessed for relevance to the flight graph problem.',
          keyFindings: [
            'Pattern 1 — Snapshot-Based: Fixed-interval snapshots with static GNN per step. Initially flagged as too computationally expensive for irregular data (later chosen when ADS-B data cadence made it feasible)',
            'Pattern 2 — Event-Driven / Continuous-Time: Graph as stream of timestamped events, updates only on events. Initially selected as backbone. Key references: Know-Evolve, TGN',
            'Pattern 3 — Hybrid Structural + Temporal: GNN for spatial structure + RNN/attention for history. Initially selected as encoder strategy. Key references: RE-NET, HTGNN',
            'Initial recommendation: Pattern 2 backbone + Pattern 3 encoder. This was later overruled in favor of Pattern 1 (see Graph Definition, Mar 20)',
            'Aviation-specific GNN work exists but focuses on trajectory prediction, not multi-relational risk from event streams',
            'Primary references: TGN (Rossi 2020), Know-Evolve (Trivedi 2017), HTGNN (Fan 2022), RE-NET (Jin 2020), GAT-LSTM (Zhu 2022)',
          ],
          ledTo: ['initial-architecture', 'graph-update-strategy'],
          tags: ['literature-review', 'patterns', 'dynamic-gnn', 'citations'],
        },
        {
          id: 'initial-architecture',
          date: '2025-12-01',
          title: 'Initial Model Architecture & Methodology',
          type: 'decision',
          summary: 'Designed the initial model architecture: a multi-stage pipeline from raw data through graph construction, GNN layers, to risk prediction. Established methodology decisions for the decoder, loss function, and GNN design.',
          body: 'The initial architecture described a heterogeneous graph with multiple node types (aircraft, flight segments, airspace nodes, accident nodes) and multiple relation types. Several of these decisions have carried forward while others were revised. The graph structure, update pattern, and training labels were all significantly changed through later work.',
          keyFindings: [
            'Pipeline: Input → Encoder → Graph Construction → GNN Layers → Decoder → Risk Output',
            'Decoder: DistMult (bilinear) — chosen over RESCAL, TransE, ComplEx. This decision carried forward',
            'Loss: Logistic cross-entropy with negative sampling. This decision carried forward',
            'GNN features: message passing, symmetric normalization, skip connections, mini-batch neighborhood sampling, inductive capability. All carried forward',
            'SUPERSEDED — Graph structure: originally heterogeneous with multiple node types → now aircraft-only nodes with two-layer multigraph',
            'SUPERSEDED — Update pattern: originally event-driven (Pattern 2) → now snapshot-based (Pattern 1)',
            'SUPERSEDED — Training labels: originally NTSB accident labels → now surrogate safety measures (LoS, well-clear, NMAC, CPA)',
            'SUPERSEDED — Node types: aircraft, flight segments, airspace nodes, accident nodes → now aircraft-only',
          ],
          figures: [
            { src: '/materials/thesis/phase3/Model_overview.png', alt: 'Early Model Architecture', caption: 'Early model architecture diagram. Several components have since been revised — see timeline for Graph Definition (Mar 20) and Surrogate Pivot (Feb 27).', layout: 'full' },
          ],
          ledTo: ['usable-data-definition'],
          motivatedBy: ['data-source-evaluation', 'literature-review-patterns'],
          tags: ['architecture', 'methodology', 'distmult', 'gnn'],
        },
        {
          id: 'raw-data-schema',
          date: '2025-12-15',
          title: 'Raw Data Schema Definition',
          type: 'report',
          summary: 'Documented the field-level schema for OpenSky state vectors, NTSB event records, and NTSB aircraft records. These definitions remained stable throughout the project.',
          keyFindings: [
            'OpenSky state vectors: time, icao24, lat/lon, velocity, heading, vertrate, callsign, onground, geoaltitude, baroaltitude',
            'NTSB events: ev_id, ntsb_no, ev_date/time, location fields, ev_highest_injury, nearest airport',
            'NTSB aircraft: ev_id, regis_no (N-number), acft_make/model, departure/destination airports',
            'Key join: N-number → ICAO24 conversion via icao-nnumber-converter-us for OpenSky-NTSB matching',
          ],
          ledTo: ['usable-data-definition', 'synthetic-pipeline'],
          tags: ['schema', 'opensky', 'ntsb', 'data-format'],
        },
      ],
    },

    // ============================================================
    // PHASE 1: Synthetic Data (Jan 14 – Feb 16, 2026)
    // ============================================================
    {
      id: 'synthetic-data',
      title: 'Synthetic Data Approach',
      dateRange: 'Jan 14 – Feb 16, 2026',
      summary: 'Attempted to build training data by matching NTSB accidents to OpenSky trajectories, then generating synthetic collisions for missing aircraft. Built a pipeline that matched 370 accident-trajectory pairs and generated 20 synthetic collision encounters.',
      outcome: 'Dropped — most incidents had only one aircraft\'s ADS-B data, synthetic collisions were unrealistic, and no near-miss data could be generated.',
      outcomeType: 'failure',
      entries: [
        {
          id: 'usable-data-definition',
          date: '2026-01-14',
          title: 'Data Quality Requirements',
          type: 'decision',
          summary: 'Defined what constitutes a "usable" accident-trajectory pair. Formalized trajectory requirements (minimum points, time alignment, etc.) into a spec enforced by pipeline code.',
          keyFindings: [
            'Established minimum trajectory point threshold for usable data',
            'Defined time alignment requirements between NTSB records and OpenSky data',
            'Created quality tiers: gold, silver, bronze based on data completeness',
          ],
          reports: [
            {
              filename: 'usable_data_definition.md',
              title: 'Usable Data Definition',
              questionAnswered: 'What data quality bar do we need before a trajectory pair is useful for training?',
              status: 'dropped',
            },
          ],
          ledTo: ['synthetic-pipeline'],
          tags: ['ntsb', 'opensky', 'data-quality'],
        },
        {
          id: 'proximity-baseline',
          date: '2026-01-14',
          title: 'Airport Proximity Baseline Analysis',
          type: 'report',
          summary: 'Baseline analysis of proximity metrics near busy airports during normal operations. Sampled major US airports to understand what "normal close" looks like so proximity alone isn\'t treated as risk.',
          keyFindings: [
            'Aircraft routinely come within small distances near airports — proximity alone is not a risk signal',
            'Need filtering logic to distinguish routine airport proximity from genuine risk',
            'This insight carried forward into the surrogate audit filtering (3 nmi + 1,500 ft buffer)',
          ],
          reports: [
            {
              filename: 'proximity_baseline_notes.md',
              title: 'Proximity Baseline Notes',
              questionAnswered: 'How close do aircraft routinely get near airports, and can we distinguish routine proximity from genuine risk?',
              status: 'dropped',
            },
          ],
          ledTo: ['surrogate-audit'],
          tags: ['opensky', 'proximity', 'airports'],
        },
        {
          id: 'pattern-mining',
          date: '2026-01-14',
          title: 'Trajectory Pattern Mining',
          type: 'report',
          summary: 'Pattern mining from trajectory features — extracting repeatable kinematic patterns to understand normal flight behavior and identify anomalies.',
          keyFindings: [
            'Attempted to identify distinct kinematic regimes (ground ops, climb, cruise, etc.)',
            'Results showed 0 ground-ops samples and limited pattern diversity',
            'Insufficient pattern variation to serve as a useful feature for the model',
          ],
          reports: [
            {
              filename: 'patterns_notes.md',
              title: 'Pattern Mining Notes',
              questionAnswered: 'Are there distinct kinematic regimes and can we bucket trajectories into them?',
              status: 'dropped',
            },
          ],
          tags: ['opensky', 'patterns'],
        },
        {
          id: 'synthetic-pipeline',
          date: '2026-01-16',
          title: 'Synthetic Pipeline Implementation',
          type: 'report',
          summary: 'Built the end-to-end synthetic data pipeline. Matched 370 NTSB accident-trajectory pairs and tiered them by quality: 212 gold, 38 silver, 22 bronze.',
          keyFindings: [
            '370 total NTSB accidents matched to OpenSky trajectories',
            'Quality tiering: 212 gold / 38 silver / 22 bronze pairs',
            'Pipeline operational but data quality insufficient for GNN training',
            'OpenSky-NTSB match rate ~40% — small GA aircraft often lack ADS-B transponders',
            'N-number to ICAO24 conversion via icao-nnumber-converter-us package',
          ],
          figures: [
            { src: '/materials/thesis/phase1/aircraft_proximity_graph.png', alt: 'Aircraft Proximity Graph - LA Area', caption: 'LA area sample: 21 aircraft, 126 proximity edges (<30km). Demonstrates spatial relationships that form the basis of proximity risk edges.', layout: 'full' },
            { src: '/materials/thesis/phase1/opensky_network_viz.png', alt: 'OpenSky Network Visualization', caption: 'OpenSky ADS-B network coverage visualization.', layout: 'half' },
            { src: '/materials/thesis/phase1/opensky_sample_viz.png', alt: 'OpenSky Sample Data', caption: 'Sample OpenSky state vector data visualization.', layout: 'half' },
            { src: '/materials/thesis/phase1/all_flights_map.png', alt: 'All Matched Flights Map', caption: 'Geographic distribution of all matched accident-trajectory flights.', layout: 'full' },
            { src: '/materials/thesis/phase1/flight_statistics.png', alt: 'Flight Statistics', caption: 'Statistical breakdown of matched flight data.', layout: 'half' },
            { src: '/materials/thesis/phase1/aircraft_network.png', alt: 'Aircraft Network', caption: 'Network graph of matched aircraft relationships.', layout: 'half' },
          ],
          reports: [
            {
              filename: 'pipeline_implementation_guide.md',
              title: 'Pipeline Implementation Guide',
              questionAnswered: 'How does the synthetic pipeline work end-to-end, and what did we get out of it?',
              status: 'dropped',
            },
          ],
          motivatedBy: ['usable-data-definition'],
          ledTo: ['incident-classification'],
          tags: ['ntsb', 'opensky', 'pipeline', 'synthetic'],
        },
        {
          id: 'incident-classification',
          date: '2026-01-29',
          title: 'Incident Classification & Narrowing',
          type: 'report',
          summary: 'Classified the 41 usable incidents into multi-aircraft conflicts (15), runway incursions (11), and wrong surface/runway events (15). Narrowed to the 8 airborne multi-aircraft conflicts with trajectory data.',
          keyFindings: [
            '41 usable incidents classified into 3 categories',
            '15 multi-aircraft conflicts, 11 runway incursions, 15 wrong surface/runway',
            'Narrowed to 8 airborne multi-aircraft conflicts with trajectory data',
            'Critical finding: 7 of 8 incidents had only ONE aircraft\'s ADS-B data',
            'The missing-aircraft problem drove the need for synthetic generation',
          ],
          figures: [
            { src: '/materials/thesis/phase1/ntsb_insights.png', alt: 'NTSB Accident Insights', caption: 'Decades of US aviation accident data: 1,500-2,000 accidents/year, top states CA/TX/FL, 53% result in no injuries.', layout: 'full' },
            { src: '/materials/thesis/phase1/ntsb_flight_status.png', alt: 'NTSB Flight Status', caption: '92.2% of accidents occur in-flight vs 4.9% on ground. Flight phase codes enable filtering for trajectory-relevant incidents.', layout: 'half' },
            { src: '/materials/thesis/phase1/ntsb_trend.png', alt: 'NTSB Accident Trends', caption: 'Historical trend analysis of NTSB accident data over time.', layout: 'half' },
            { src: '/materials/thesis/phase1/trajectory_CEN20LA429.png', alt: 'Matched Trajectory CEN20LA429', caption: 'Example matched trajectory (CEN20LA429): 4-panel visualization showing flight path, altitude profile, vertical rate, and ground speed.', layout: 'full' },
          ],
          reports: [
            {
              filename: 'classification.md',
              title: 'Incident Classification',
              questionAnswered: 'Of our real NTSB incidents with trajectory data, which ones are useful and how should we categorize them?',
              status: 'superseded',
            },
            {
              filename: 'multi_aircraft_conflicts_report/classification.md',
              title: 'Multi-Aircraft Conflicts Classification',
              questionAnswered: 'Which incidents involve two aircraft in the air with usable trajectories?',
              status: 'current',
            },
          ],
          motivatedBy: ['synthetic-pipeline'],
          ledTo: ['canonical-schema'],
          tags: ['ntsb', 'classification', 'multi-aircraft'],
        },
        {
          id: 'canonical-schema',
          date: '2026-02-04',
          title: 'Canonical Schema & Synthetic Generation Plan',
          type: 'decision',
          summary: 'Designed a canonical data schema to standardize real and synthetic data formats. Step 5 tackled synthetic collision generation to fill the missing-aircraft gap — 7 of 8 incidents had only 1 aircraft\'s trajectory.',
          body: 'The canonical approach mapped OpenSky columns to a unified schema and defined the transform pipeline. The core problem was stark: 7 of 8 real airborne multi-aircraft conflicts had only one aircraft\'s ADS-B data, and the single incident with both aircraft had data from the wrong time window. Synthetic generation was the proposed solution.',
          reports: [
            {
              filename: 'PLAN.md',
              title: 'Canonical Schema Plan (Steps 1-4)',
              questionAnswered: 'Can we standardize our data format so real and synthetic data can be merged?',
              status: 'dropped',
            },
            {
              filename: 'PLAN_step5.md',
              title: 'Synthetic Generation Plan (Step 5)',
              questionAnswered: 'Can we generate synthetic collision data to fill the missing-aircraft gap?',
              status: 'dropped',
            },
          ],
          motivatedBy: ['incident-classification'],
          ledTo: ['canonical-report'],
          tags: ['synthetic', 'schema', 'data-generation'],
        },
        {
          id: 'canonical-report',
          date: '2026-02-06',
          title: 'Synthetic Pipeline Results — Limitations Found',
          type: 'failure',
          summary: 'Generated 20 synthetic collision encounters, but only collisions (y=1) — no near-misses. Revealed fundamental limitations: dead-reckoned positions, rotation distortion, perfect 0.0m collision separation. This was the inflection point that led to the surrogate pivot.',
          keyFindings: [
            'Pipeline produced 20 synthetic collisions end-to-end',
            'Only collisions generated — no near-miss encounters (the "near-miss gap")',
            'Known fidelity issues: dead-reckoned positions, rotation distortion',
            'All synthetic collisions had perfect 0.0m separation — unrealistic',
            'This failure was the direct trigger for exploring surrogate safety measures',
          ],
          figures: [
            { src: '/materials/thesis/phase1/synthetic_1_summary.png', alt: 'Synthetic Data Summary', caption: 'Overview of the 20 generated synthetic collision encounters.', layout: 'full' },
            { src: '/materials/thesis/phase1/synthetic_2_collision.png', alt: 'Collision Scenarios', caption: 'Generated collision scenario visualizations.', layout: 'half' },
            { src: '/materials/thesis/phase1/synthetic_3_aircraft.png', alt: 'Aircraft Type Distribution', caption: 'Aircraft type distribution in synthetic dataset.', layout: 'half' },
            { src: '/materials/thesis/phase1/synthetic_4_geographic.png', alt: 'Geographic Distribution', caption: 'Geographic distribution of synthetic collision events.', layout: 'half' },
            { src: '/materials/thesis/phase1/synthetic_5_proximity.png', alt: 'Proximity Statistics', caption: 'Proximity distance metrics from synthetic encounters.', layout: 'half' },
            { src: '/materials/thesis/phase1/synthetic_6_collision_details.png', alt: 'Collision Details', caption: 'Detailed collision parameters and trajectories.', layout: 'full' },
          ],
          reports: [
            {
              filename: 'REPORT.md',
              title: 'Canonical Pipeline Final Report',
              questionAnswered: 'Does the canonical synthetic pipeline produce usable training data?',
              status: 'dropped',
            },
          ],
          motivatedBy: ['canonical-schema'],
          ledTo: ['last-synthetic-efforts', 'deep-research'],
          tags: ['synthetic', 'failure', 'collision-generation'],
        },
        {
          id: 'last-synthetic-efforts',
          date: '2026-02-16',
          title: 'Final Synthetic Data Attempts — Approach Dropped',
          type: 'failure',
          summary: 'Last attempts to salvage the synthetic approach: an updated classification (v2) and a hybrid simulator proposal for near-miss generation. Both were ultimately dropped — the simulator was too complex for thesis scope, and the underlying data gap couldn\'t be solved synthetically.',
          body: 'The simulator proposal identified the "near-miss gap" — the synthetic pipeline could only produce collisions, but the model needs close-but-safe encounters to learn discrimination. While technically promising, the hybrid simulator would have required building a full flight dynamics model, which was beyond thesis scope. The surrogate pivot offered a cleaner path.',
          reports: [
            {
              filename: 'classification_v2.md',
              title: 'Classification v2',
              questionAnswered: 'Can the synthetic collision data be improved enough to use?',
              status: 'dropped',
            },
            {
              filename: 'simulator_proposal.md',
              title: 'Hybrid Simulator Proposal',
              questionAnswered: 'Could a more sophisticated simulator solve the data problem?',
              status: 'dropped',
            },
          ],
          motivatedBy: ['canonical-report'],
          ledTo: ['deep-research'],
          tags: ['synthetic', 'simulator', 'near-miss'],
        },
      ],
    },

    // ============================================================
    // PHASE 2: The Surrogate Pivot (Feb 19 – Mar 6, 2026)
    // ============================================================
    {
      id: 'surrogate-pivot',
      title: 'The Surrogate Pivot',
      dateRange: 'Feb 19 – Mar 6, 2026',
      summary: 'Literature review revealed surrogate safety measures (LoS, well-clear, NMAC, CPA) as well-established alternatives to direct accident labels. Empirical validation on real LA Basin data confirmed these signals are dense enough for training after airport filtering.',
      outcome: 'Validated — surrogate signals provide dense, computable training labels while preserving the core architecture.',
      outcomeType: 'success',
      entries: [
        {
          id: 'deep-research',
          date: '2026-02-19',
          title: 'Literature Review — Surrogate Safety Measures',
          type: 'report',
          summary: 'Deep research report on surrogate safety measures for airspace collision risk modeling. Reviewed aviation safety literature on surrogates, mapping them to thesis architecture constraints: computable at event time, dense enough for learning, supports encounter-to-accident interpretation.',
          keyFindings: [
            'Surrogate safety measures are well-established in aviation safety research',
            'Key surrogates identified: LoS (Loss of Separation), well-clear, NMAC (Near Mid-Air Collision), CPA (Closest Point of Approach)',
            'Surrogates must be computable from ADS-B data at event time',
            'Signal density must be sufficient for GNN training (hundreds+ events per hour)',
            'Architecture constraints from full_amm_context.md shaped which surrogates were viable',
          ],
          reports: [
            {
              filename: 'deep-research-report.md',
              title: 'Surrogate Safety Measures Research',
              questionAnswered: 'What does the research literature say about alternatives to direct accident labels?',
              status: 'current',
            },
          ],
          motivatedBy: ['canonical-report', 'last-synthetic-efforts'],
          ledTo: ['pivot-decision'],
          tags: ['literature-review', 'surrogates', 'safety-measures'],
        },
        {
          id: 'pivot-decision',
          date: '2026-02-27',
          title: 'The Pivotal Decision — Surrogate Labels',
          type: 'pivot',
          summary: 'The defining document for the project\'s current direction. Established that the thesis architecture stays the same but training labels change from accidents to surrogate safety measures. Defines severity tiers, published thresholds, and the MVP training plan.',
          body: 'This was the pivotal moment: rather than trying to find or generate accident data (which proved intractable), we use established aviation safety metrics that are abundantly computable from the same ADS-B data we already collect. The model learns to predict proximity risk using surrogate signals as training labels, with severity tiers mapping to different safety thresholds.',
          keyFindings: [
            'Core architecture preserved — only the training labels changed',
            'Surrogate severity tiers defined with published FAA/ICAO thresholds',
            'LoS: categorical separation violation indicator',
            'Well-clear: categorical safety boundary with published thresholds',
            'NMAC: categorical near mid-air collision indicator',
            'CPA (Closest Point of Approach): continuous metric — identified as strongest signal',
            'MVP training plan established for initial model validation',
          ],
          reports: [
            {
              filename: 'pivot_report.md',
              title: 'Surrogate Pivot Report',
              questionAnswered: 'How do we solve the label sparsity problem without changing the core architecture?',
              status: 'current',
            },
          ],
          motivatedBy: ['deep-research'],
          ledTo: ['surrogate-audit'],
          tags: ['pivot', 'surrogates', 'architecture', 'labels'],
        },
        {
          id: 'surrogate-audit',
          date: '2026-03-06',
          title: 'LA Basin Empirical Validation',
          type: 'result',
          summary: 'Empirical audit of surrogate safety signals on 4 hours of LA Basin ADS-B data. Confirmed surrogates are viable after airport filtering.',
          keyFindings: [
            'Raw surrogate flags dominated by airport noise: 98% of NMAC, 88% of well-clear flags',
            'Airport filtering (3 nmi + 1,500 ft buffer) dramatically reduces noise',
            'After filtering, LoS remains viable with ~6,300 events per 4 hours',
            'CPA distance is the strongest continuous signal: 26,600+ non-airport pairs within 5 km',
            'Surrogate signals are dense enough for GNN training — orders of magnitude more than accident labels',
            'Filtering approach informed by earlier proximity baseline analysis',
          ],
          figures: [
            { src: '/materials/thesis/phase2/audit_01_filter_impact.png', alt: 'Airport Filter Impact', caption: 'Impact of airport proximity filtering on surrogate flag counts. 3 nmi + 1,500 ft buffer removes 98% of NMAC noise.', layout: 'full' },
            { src: '/materials/thesis/phase2/audit_02_cpa_distribution.png', alt: 'CPA Distribution', caption: 'Distribution of Closest Point of Approach distances — the strongest continuous training signal.', layout: 'half' },
            { src: '/materials/thesis/phase2/audit_03_spatial_heatmap.png', alt: 'Spatial Heatmap', caption: 'Geographic heatmap of surrogate safety events in the LA Basin.', layout: 'half' },
            { src: '/materials/thesis/phase2/audit_04_altitude_breakdown.png', alt: 'Altitude Breakdown', caption: 'Altitude distribution of surrogate safety events.', layout: 'half' },
            { src: '/materials/thesis/phase2/audit_05_cpa_threshold_curve.png', alt: 'CPA Threshold Curve', caption: 'CPA event count as a function of distance threshold — shows rapid increase in events at larger thresholds.', layout: 'half' },
            { src: '/materials/thesis/phase2/audit_06_time_of_day.png', alt: 'Time of Day Analysis', caption: 'Temporal distribution of surrogate events across the 4-hour observation window.', layout: 'full' },
          ],
          reports: [
            {
              filename: 'surrogate_audit_report.md',
              title: 'Surrogate Audit Report',
              questionAnswered: 'Are surrogate safety signals actually dense enough in real data, and can we filter out airport noise?',
              status: 'current',
            },
          ],
          motivatedBy: ['pivot-decision', 'proximity-baseline'],
          ledTo: ['graph-definition', 'scaled-data-collection'],
          tags: ['surrogates', 'validation', 'la-basin', 'airport-filtering'],
        },
      ],
    },

    // ============================================================
    // PHASE 3: Graph & Pipeline Build-Out (Mar 12 – present)
    // ============================================================
    {
      id: 'graph-build-out',
      title: 'Graph & Pipeline Build-Out',
      dateRange: 'Mar 12, 2026 – present',
      summary: 'With the surrogate approach validated, work shifted to defining the formal graph schema, evaluating update strategies, and scaling data collection to the top 5 US airports by passenger traffic.',
      outcome: 'In progress — graph schema finalized, data collection scaling to national airports.',
      outcomeType: 'ongoing',
      entries: [
        {
          id: 'graph-update-strategy',
          date: '2026-03-13',
          title: 'Graph Update Strategy Evaluation',
          type: 'decision',
          summary: 'Evaluated three graph update patterns: event-only, periodic (constant-interval snapshots), and hybrid. Initially recommended Pattern 2 (event-driven) as backbone with Pattern 3 (hybrid) as encoder, but this was later overruled in favor of Pattern 1 (snapshot-based) in the graph definition report.',
          keyFindings: [
            'Three update patterns evaluated: event-only, periodic, hybrid',
            'This report initially recommended Pattern 2 (event-driven) + Pattern 3 (hybrid encoder)',
            'Identified that event-only risks stale node states during quiet periods',
            'Later decision (graph_definition_report): Pattern 1 (snapshot-based) chosen instead',
            'Rationale: ADS-B data arrives at ~1s intervals, making fixed snapshots simpler and natural',
            'Early concern about Pattern 1 computational cost resolved — snapshots match data cadence',
          ],
          reports: [
            {
              filename: 'graph_updating report.md',
              title: 'Graph Update Strategy Report',
              questionAnswered: 'Should our graph update only on events, or does it need periodic refreshes too?',
              status: 'current',
            },
          ],
          ledTo: ['graph-definition'],
          tags: ['graph', 'update-strategy', 'architecture'],
        },
        {
          id: 'graph-definition',
          date: '2026-03-20',
          title: 'Definitive Graph Schema',
          type: 'decision',
          summary: 'The definitive graph schema document. Defines a two-layer multigraph with aircraft nodes and directed proximity edges carrying raw separation distance. Uses Pattern 1 (snapshot-based) updates — the graph is rebuilt at fixed intervals, replacing the earlier event-driven design.',
          body: 'The graph uses a two-layer multigraph architecture: Layer 1 for proximity relationships and Layer 2 for encounter geometry. A planned Layer 3 (shared-corridor) was dropped as unnecessary. Aircraft are the only node type, with directed proximity edges storing raw separation distance — letting the model learn which distances matter rather than imposing hard thresholds. Surrogate safety measures (LoS, well-clear, NMAC, CPA) are mapped to edge attributes. Key architectural shift: Pattern 1 (snapshot-based) was chosen over Pattern 2 (event-driven) for updates. ADS-B state vectors arrive at ~1-second intervals, so fixed-interval snapshots match the natural data cadence and avoid the complexity of asynchronous event handling.',
          keyFindings: [
            'Two-layer multigraph: proximity + encounter geometry (Layer 3 shared-corridor dropped)',
            'Aircraft-only nodes with directed proximity edges',
            'Proximity edges store raw separation distance — model learns thresholds',
            'Surrogate definitions mapped to edge attributes with validated event counts',
            'Pattern 1 (snapshot-based) chosen for updates — graph rebuilt at fixed intervals (~1s)',
            'Replaces earlier Pattern 2 (event-driven) design — snapshots match ADS-B data cadence',
            'Computational concern from early work addressed: snapshots are feasible because ADS-B data is already ~1s resolution',
          ],
          reports: [
            {
              filename: 'graph_definition_report.md',
              title: 'Graph Definition Report',
              questionAnswered: 'What exactly are the nodes, edges, and attributes in our graph, and how do surrogates map onto them?',
              status: 'current',
            },
          ],
          motivatedBy: ['surrogate-audit', 'graph-update-strategy'],
          ledTo: ['scaled-data-collection'],
          tags: ['graph', 'schema', 'multigraph', 'surrogates'],
        },
        {
          id: 'scaled-data-collection',
          date: '2026-03-24',
          title: 'Scaled Data Collection — Top 5 US Airports',
          type: 'data-collection',
          summary: 'Scaled the 4-hour LA Basin pilot to a representative national dataset. Defines study scope: top 5 US airports by passenger traffic (KATL, KDFW, KDEN, KORD, KLAX), 24-hour ADS-B query windows.',
          keyFindings: [
            'Study scope: top 5 US airports by passenger traffic',
            'KATL (Atlanta), KDFW (Dallas-Fort Worth), KDEN (Denver), KORD (Chicago O\'Hare), KLAX (Los Angeles)',
            '24-hour ADS-B query windows per airport',
            'FAA airspace class definitions integrated for context',
            'Per-airport analysis: filter impact, spatial heatmaps, 3D trajectories, aircraft overview',
          ],
          figures: [
            { src: '/materials/thesis/phase3/airports/la/01_airport_filter_impact.png', alt: 'LA Filter Impact', caption: 'Airport proximity filter effectiveness at KLAX.', layout: 'grid-4' },
            { src: '/materials/thesis/phase3/airports/la/03_spatial_heatmap.png', alt: 'LA Spatial Heatmap', caption: 'Spatial heatmap of aircraft proximity events near KLAX.', layout: 'grid-4' },
            { src: '/materials/thesis/phase3/airports/la/3d_trajectories.png', alt: 'LA 3D Trajectories', caption: '3D trajectory visualization in KLAX airspace.', layout: 'grid-4' },
            { src: '/materials/thesis/phase3/airports/la/aircraft_overview.png', alt: 'LA Aircraft Overview', caption: 'Aircraft statistics overview for KLAX.', layout: 'grid-4' },
          ],
          reports: [
            {
              filename: 'airport_reference_24hr.md',
              title: 'Airport Reference (24hr)',
              questionAnswered: 'How do we scale our 4-hour LA Basin pilot to a representative national dataset?',
              status: 'current',
            },
          ],
          motivatedBy: ['surrogate-audit', 'graph-definition'],
          tags: ['data-collection', 'airports', 'scaling', 'opensky'],
        },
      ],
    },
  ],
}

// Airport data for the tabbed airport selector in Phase 3
export const airportData = [
  {
    code: 'KLAX',
    name: 'Los Angeles',
    plots: [
      { src: '/materials/thesis/phase3/airports/la/01_airport_filter_impact.png', alt: 'Filter Impact', caption: 'Airport proximity filter effectiveness at KLAX.' },
      { src: '/materials/thesis/phase3/airports/la/03_spatial_heatmap.png', alt: 'Spatial Heatmap', caption: 'Spatial heatmap of proximity events near KLAX.' },
      { src: '/materials/thesis/phase3/airports/la/3d_trajectories.png', alt: '3D Trajectories', caption: '3D trajectory visualization in KLAX airspace.' },
      { src: '/materials/thesis/phase3/airports/la/aircraft_overview.png', alt: 'Aircraft Overview', caption: 'Aircraft statistics for KLAX.' },
    ],
  },
  {
    code: 'KATL',
    name: 'Atlanta',
    plots: [
      { src: '/materials/thesis/phase3/airports/atlanta/01_airport_filter_impact.png', alt: 'Filter Impact', caption: 'Airport proximity filter effectiveness at KATL.' },
      { src: '/materials/thesis/phase3/airports/atlanta/03_spatial_heatmap.png', alt: 'Spatial Heatmap', caption: 'Spatial heatmap of proximity events near KATL.' },
      { src: '/materials/thesis/phase3/airports/atlanta/3d_trajectories.png', alt: '3D Trajectories', caption: '3D trajectory visualization in KATL airspace.' },
      { src: '/materials/thesis/phase3/airports/atlanta/aircraft_overview.png', alt: 'Aircraft Overview', caption: 'Aircraft statistics for KATL.' },
    ],
  },
  {
    code: 'KDFW',
    name: 'Dallas-Fort Worth',
    plots: [
      { src: '/materials/thesis/phase3/airports/dfw/01_airport_filter_impact.png', alt: 'Filter Impact', caption: 'Airport proximity filter effectiveness at KDFW.' },
      { src: '/materials/thesis/phase3/airports/dfw/03_spatial_heatmap.png', alt: 'Spatial Heatmap', caption: 'Spatial heatmap of proximity events near KDFW.' },
      { src: '/materials/thesis/phase3/airports/dfw/3d_trajectories.png', alt: '3D Trajectories', caption: '3D trajectory visualization in KDFW airspace.' },
      { src: '/materials/thesis/phase3/airports/dfw/aircraft_overview.png', alt: 'Aircraft Overview', caption: 'Aircraft statistics for KDFW.' },
    ],
  },
  {
    code: 'KDEN',
    name: 'Denver',
    plots: [
      { src: '/materials/thesis/phase3/airports/denver/01_airport_filter_impact.png', alt: 'Filter Impact', caption: 'Airport proximity filter effectiveness at KDEN.' },
      { src: '/materials/thesis/phase3/airports/denver/03_spatial_heatmap.png', alt: 'Spatial Heatmap', caption: 'Spatial heatmap of proximity events near KDEN.' },
      { src: '/materials/thesis/phase3/airports/denver/3d_trajectories.png', alt: '3D Trajectories', caption: '3D trajectory visualization in KDEN airspace.' },
      { src: '/materials/thesis/phase3/airports/denver/aircraft_overview.png', alt: 'Aircraft Overview', caption: 'Aircraft statistics for KDEN.' },
    ],
  },
  {
    code: 'KORD',
    name: 'Chicago O\'Hare',
    plots: [
      { src: '/materials/thesis/phase3/airports/chicago/01_airport_filter_impact.png', alt: 'Filter Impact', caption: 'Airport proximity filter effectiveness at KORD.' },
      { src: '/materials/thesis/phase3/airports/chicago/03_spatial_heatmap.png', alt: 'Spatial Heatmap', caption: 'Spatial heatmap of proximity events near KORD.' },
      { src: '/materials/thesis/phase3/airports/chicago/3d_trajectories.png', alt: '3D Trajectories', caption: '3D trajectory visualization in KORD airspace.' },
      { src: '/materials/thesis/phase3/airports/chicago/aircraft_overview.png', alt: 'Aircraft Overview', caption: 'Aircraft statistics for KORD.' },
    ],
  },
]
